from typing import Protocol


class EngineAdapter(Protocol):
    @property
    def engine_id(self) -> str: ...

    def capabilities(self) -> dict: ...

    def health(self) -> dict: ...

    def load_model(self, model: dict) -> None: ...

    def unload_model(self, model_id: str) -> None: ...

    def synthesize(self, text: str, speed: float, profile: dict) -> bytes: ...
